version: '3.8'
services:
  # --- Databases ---
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ecommerce-network

  # --- Infrastructure ---
  service-registry:
    build: ./service-registery
    container_name: service-registry
    ports:
      - "8761:8761"
    environment:
      - EUREKA_CLIENT_REGISTERWITHEUREKA=false
      - EUREKA_CLIENT_FETCHREGISTRY=false
    networks:
      - ecommerce-network

  config-server:
    build: ./Config-Server
    container_name: config-server
    ports:
      - "8888:8888"
    depends_on:
      - service-registry
    networks:
      - ecommerce-network

  zuul-api-gateway:
    build: ./zuul-api-gateway
    container_name: zuul-api-gateway
    ports:
      - "8765:8765"
    depends_on:
      - service-registry
      - config-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - ecommerce-network



  # --- Microservices ---
  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "9002:9002"
    depends_on:
      - service-registry
      - config-server
      - postgres-db
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/ecommerce
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    networks:
      - ecommerce-network

  order-service:
    build: ./OrderService
    container_name: order-service
    ports:
      - "9003:9003"
    depends_on:
      - service-registry
      - config-server
      - postgres-db
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/ecommerce
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    networks:
      - ecommerce-network

  inventory-service:
    build: ./Inventory-Service
    container_name: inventory-service
    ports:
      - "9004:9004"
    depends_on:
      - service-registry
      - config-server
      - postgres-db
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/ecommerce
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    networks:
      - ecommerce-network

  customer-service:
    build: ./CustomerService
    container_name: customer-service
    ports:
      - "9001:9001"
    depends_on:
      - service-registry
      - config-server
      - postgres-db
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/ecommerce
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    networks:
      - ecommerce-network

  shipping-service:
    build: ./shipping-service
    container_name: shipping-service
    ports:
      - "9006:9006"
    depends_on:
      - service-registry
      - config-server
      - postgres-db
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/ecommerce
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

volumes:
  postgres-data:
