global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'shipping-service:9006'
          - 'zuul-api-gateway:8080'
          - 'product-service:9002'
          - 'inventory-service:9003'
          - 'order-service:9005'
          - 'cart-service:9004'
          - 'customer-service:9001'
