spring.application.name=Cart-Service

server.port=9004

spring.h2.console.enabled=true
spring.datasource.url=jdbc:postgresql://postgres-db:5432/ecommerce
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=root
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
