server.port=8080
spring.application.name=Api-Gateway

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Gateway Routes
spring.cloud.gateway.routes[0].id=shipping-service
spring.cloud.gateway.routes[0].uri=lb://Shipping-Service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/shippingservice/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/api/shippingservice/(?<segment>.*), /$\\{segment}

spring.cloud.gateway.routes[1].id=product-service
spring.cloud.gateway.routes[1].uri=lb://Product-Service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/productservice/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/api/productservice/(?<segment>.*), /$\\{segment}

spring.cloud.gateway.routes[2].id=cart-service
spring.cloud.gateway.routes[2].uri=lb://Cart-Service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/cartservice/**
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/api/cartservice/(?<segment>.*), /api/$\\{segment}

spring.cloud.gateway.routes[3].id=inventory-service
spring.cloud.gateway.routes[3].uri=lb://Inventory-Service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/inventoryservice/**
spring.cloud.gateway.routes[3].filters[0]=RewritePath=/api/inventoryservice/(?<segment>.*), /api/$\\{segment}

spring.cloud.gateway.routes[4].id=order-service
spring.cloud.gateway.routes[4].uri=lb://Order-Service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/orderservice/**
spring.cloud.gateway.routes[4].filters[0]=RewritePath=/api/orderservice/(?<segment>.*), /api/$\\{segment}

spring.cloud.gateway.routes[5].id=customer-service
spring.cloud.gateway.routes[5].uri=lb://Customer-Service
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/customerservice/**
spring.cloud.gateway.routes[5].filters[0]=RewritePath=/api/customerservice/(?<segment>.*), /$\\{segment}

# Auto-discover services from Eureka
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true