server.port=8888
spring.application.name=Config-Server
spring.cloud.config.server.git.uri=https://github.com/swarnim0308/Ecommerce-Microservices.git
spring.cloud.config.server.git.search-paths=config-properties
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.default-label=jdk_update
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true