server.port=8888
spring.application.name=Config-Server
spring.cloud.config.server.git.uri=https://github.com/swarnim0308/Ecommerce-Microservices.git
spring.cloud.config.server.git.search-paths=config-properties
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.default-label=jdk_update
# Enable verbose logging
logging.level.org.springframework.cloud.config=DEBUG 
logging.level.org.eclipse.jgit=DEBUG